backend:
  name: github
  repo: "breeze256/brz256-blog"
  branch: main
  base_url: https://decap.breeze256.ink
  auth_endpoint: /auth

locale: zh_Hans

media_folder: "source/images"
public_folder: "/images"

collections:
  - name: "post"
    label: "Posts"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "更新日期", name: "updated", widget: "datetime", required: false }
      - { label: "隐藏 (草稿)", name: "draft", widget: "boolean", default: true }
      - { label: "标签", name: "tags", widget: "list" }
      - { label: "分类", name: "categories", widget: "list" }
      - { label: "正文", name: "body", widget: "markdown" }